//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gBudget2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataInfo
    {
        public int DatainfoID { get; set; }
        public int Amount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> MechantID { get; set; }
        public string Note { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual Mechant Mechant { get; set; }
    }
}
